### ISSUE TITLE
After moving target/release/warp-rpc, fails with: Error: missing field `zec`

### ISSUE THREAD

**Issue by skyl** [hhanh00/zcash-sync#3]
I follow the README and successfully build the `warp-rpc` and to some successful `curl` commands and it seems to work. It's funny though, if I move the binary to a different path it doesn't work. I thought it might be some relative paths in `target/` somehow. But, even moving the entire parent `zcash-sync` dir results in a mysterious error:

```
$ cp -r zcash-sync ~/tmp
$ ~/tmp/zcash-sync/target/release/warp-rpc 
Error: missing field `zec`
```

Am I wrong to assume that the `warp-rpc` file should be able to be moved and still function?

**Comment by hhanh00** [comment]
Looks like it cannot find the config file...
