### ISSUE TITLE
reset_app is missing the call for arrrr

### ISSUE THREAD

**Issue by defuse** [hhanh00/zcash-sync#5]
https://github.com/hhanh00/zcash-sync/blob/267192c42c9f7f49a5c3c94a8c3c60eccc71cd7b/src/api/dart_ffi.rs#L129-L136

I believe there should be a `crate::api::account::reset_db(2)?;` in there.

**Comment by hhanh00** [comment]
Yeah, but pirate coin is not officially supported and is dead code.
