### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by davezhang1116** [hhanh00/zcash-sync#7]
Is this normal, I have tried multiple commits and got the same errors
command: cargo b --release --bin warp-rpc --features=rpc
cargo: 1.67.1 (8ecd4f20a 2023-01-10) 
rustc: 1.67.1 (d5a82bbd2 2023-02-07)
![image](https://user-images.githubusercontent.com/94804095/222982382-f0cbeaa9-674b-442e-839d-030cb3cdbc2c.png)

**Comment by davezhang1116** [comment]
is it possible for you to make a release

**Comment by hhanh00** [comment]
There are Cargo overrides that need to be added to your root Cargo.toml

https://github.com/hhanh00/zcash-sync/blob/1a2dbc991fe877783aa7ef3c38ab323a0d220aa5/Cargo.toml#L158

**Comment by davezhang1116** [comment]
It still shows the same error. Could you release some executable files?

**Comment by hhanh00** [comment]
It should work now.

**Comment by davezhang1116** [comment]
it shows the exact errors again. what version of rust compiler do you use?

**Comment by hhanh00** [comment]
Did you uncomment the overrides in Cargo.toml?

**Comment by davezhang1116** [comment]
it works now, thanks
