### ISSUE TITLE
Is `sign` no longer supported?

### ISSUE THREAD

**Issue by conradoplg** [hhanh00/zcash-sync#9]
I'm interested in [offline signing](https://ywallet.app/advanced/cold-storage/#command-line-tool) but the `sign` tool seems to be commented out in `Cargo.toml`. If I uncomment it and try to build it, I get a compilation error. Is it no longer supported?

Thanks!

**Comment by hhanh00** [comment]
It's been deprecated in favor of using the YWallet UI. But it's not difficult to bring it back since it's just a thin wrapper around the sign fn. I may fix the code when I have the time.
